### PR TITLE
fix: emit current folder

### LINKED ISSUE #39: Select current folder emits empty array
Bugreport by a partner: file picker in `location-picker` mode emits an empty array on  "Select current folder" button click

### PR DESCRIPTION
**Pull request by LukasHirt**
When selecting the current folder in the location picker, an empty array has been emitted. We've fixed this by emitting the current folder.

Short note: this is our first feature with integration tests 🥳 

- fixes #39

### CODE REVIEW

**Review by pascalwengerter — APPROVED** [review]
Changes look good, I would've loved to have both possibilities in `emitSelectedResources()` covered by test cases but not strictly necessary 😉

**Review by kulmann — APPROVED** [review]
💪  and 🥳 for the integration test!

**Comment by kulmann** [comment]
> Changes look good, I would've loved to have both possibilities in `emitSelectedResources()` covered by test cases but not strictly necessary 😉

Read this too late. Yes, even more test coverage would be awesome of course :-)

**Comment by LukasHirt** [comment]
> I would've loved to have both possibilities in emitSelectedResources() covered by test cases but not strictly necessary

Location variant will be fully covered via integration tests here #46

**Pull request merged**
